#! /bin/sh

# Copyright (C) 2016,2018 Tomoyuki Fujimori <moyu@dromozoa.com>
#
# This file is part of dromozoa-hook.
#
# dromozoa-hook is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# dromozoa-hook is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with dromozoa-hook.  If not, see <http://www.gnu.org/licenses/>.

if leaks -h >/dev/null 2>&1
then
  dromozoa_dirname() {
    expr  "X$1" : '\(X.*[^/]\)//*[^/][^/]*/*$' \
      '|' "X$1" : '\(X//\)[^/]' \
      '|' "X$1" : '\(X//\)$' \
      '|' "X$1" : '\(X/\)' \
      '|' X. | sed 's/^.//'
  }

  dromozoa_memcheck() {
    hook=$1
    shift
    if test -f "$hook"
    then
      case X$TMPDIR in
        X) TMPDIR=/tmp;;
      esac
      tmp=`(umask 077 && mktemp "$TMPDIR/dromozoa-XXXXXX" 2>/dev/null || :)`
      case X$tmp in
        X) tmp=$TMPDIR/dromozoa-$$-$RANDOM;;
      esac
      trap "rm -f '$tmp'" 0
      env \
        DROMOZOA_HOOK_ATEXIT='leaks "$DROMOZOA_HOOK_PID"; echo "$?" >"$DROMOZOA_HOOK_TMP"' \
        DROMOZOA_HOOK_TMP="$tmp" \
        DYLD_INSERT_LIBRARIES="$hook" \
        MallocStackLoggingNoCompact=1 \
        MallocScribble=1 \
        MallocPreScribble=1 \
          "$@"
      status=$?
      case X$status in
        X0) ;;
        *) exit "$status";;
      esac
      status=`cat "$tmp"`
      case X$status in
        X) echo "[dromozoa-hook] cannot hook (maybe setuid/setgid binary or signed with entitlements)" >&2; exit 1;;
        X0) ;;
        *) exit "$status";;
      esac
      exit 0
    fi
  }

  here=`dromozoa_dirname "$0"`
  here=`(cd "$here" && pwd)`
  root=`(cd "$here/.." && pwd)`
  if test -f "$here/.libs/libdromozoa-hook.dylib"
  then
    dromozoa_memcheck "$here/.libs/libdromozoa-hook.dylib" "$@"
  elif test -f "$root/lib/libdromozoa-hook.la"
  then
    . "$root/lib/libdromozoa-hook.la"
    dromozoa_memcheck "$libdir/$dlname" "$@"
  else
    echo "[dromozoa-hook] cannot find libdromozoa-hook" >&2
  fi
elif valgrind --version 2>&1
then
  exec valgrind \
    --track-fds=yes \
    --error-exitcode=1 \
    --leak-check=full \
    --show-reachable=yes \
    --track-origins=yes \
      "$@"
fi
exit 1
